version: '3.8'

x-common-variables: &common-variables
  DB_HOST: mysql_db
  MYSQL_DATABASE: roots
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD

  apache:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    volumes:
      - ./proxy/conf:/etc/apache2/sites-enabled
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db
    restart: always
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    ports: 
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8000:8080
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db